// 三阶段/w2_Vue/app/src/components/TodoList/TodoForm.vue
<template>
    <div class="input-group">
            <input type="text" ref="input" class="form-control" v-model="todo" @keyup.enter="addItem">
            <button class="btn btn-primary" type="button" @click="addItem">添加</button>
          </div>
</template>
<script>
export default {
    name:'TodoForm',
    data(){
        return {
            todo:''
        }
    },
    methods:{
        addItem(){
            this.$emit('additem',this.todo);

            this.todo = '';
            this.$refs.input.focus();
        }
    }
}
</script>

// 三阶段/w5_React/src/components/Todolist/TodoForm.js
import React, { Component } from 'react'

class TodoForm extends Component {
    constructor(props){
        super(props);

        this.state = {
            todo:''
        }

        this.changeTodo = this.changeTodo.bind(this);
    }
    changeTodo(e){
        this.setState({
            todo:e.currentTarget.value
        })
    }
    render(){
        const {additem} = this.props
        const {todo} = this.state
        return (
            <div className="todo-form">
                <input value={todo} onChange={this.changeTodo} ref={(el)=>{
                    this.todo = el;
                }} />
                {/* <button onClick={additem.bind(this,todo)}>添加</button> */}
                <button onClick={()=>{
                    additem(todo);
                    this.setState({
                        todo:''
                    })

                    this.todo.focus();
                }}>添加</button>
            </div>
        )
    }
}

export default TodoForm;
