// 三阶段/w5_React/src/components/Todolist/TodoItem.js
import React from 'react'

import TodoButton from './TodoButton'
import ctx from './context'

function TodoItem({ item, idx, onComplete, onRemove }) {
    return (
        <ctx.Consumer>
            {
                (value) => {
                    console.log('values=', value);
                    return (
                        <tr onClick={value.selectItem.bind(null,item.id)}>
                            <td><input type="checkbox" checked={item.checked} readOnly /></td>
                            <td>{idx + 1}</td>
                            <td>{item.todo}</td>
                            <td>{item.complete ? '是' : '否'}</td>
                            <td>
                                {/* <button onClick={onComplete.bind(null,item.id)}>完成</button>
                <button onClick={onRemove.bind(null,item.id)}>删除</button>
                <button onClick={()=>{
                    onRemove(item.id);
                }}>删除</button> */}

                                {/* <TodoButton onClick={onComplete.bind(null,item.id)}>
                    <strong>完成</strong><i>xxx</i>
                </TodoButton>
                <TodoButton onClick={onRemove.bind(null,item.id)}>删除</TodoButton> */}
                                {/* <TodoButton onClick={onRemove.bind(null,item.id)}>{
                    (num)=>{
                        return <span>span{num}</span>
                    }
                }</TodoButton> */}

                                <TodoButton onClick={value.completeItem.bind(null, item.id)}>
                                    <strong>完成</strong><i>xxx</i>
                                </TodoButton>
                                <TodoButton onClick={value.removeItem.bind(null, item.id)}>删除</TodoButton>

                            </td>
                        </tr>
                    )
                }
            }

        </ctx.Consumer>
    )
}

export default TodoItem;

// 三阶段/w2_Vue/app/src/components/TodoList/TodoItem.vue
<template>
    <tr :class="{'table-primary':item.checked}">
        <td><input type="checkbox" v-model="item.checked" /></td>
        <td>{{idx+1}}</td>
        <td>{{item.todo}}</td>
        <td>{{item.addtime}}</td>
        <td>{{item.complete ? '是' : '否'}}</td>
        <td>
            <div class="btn-group btn-group-sm">
                <!-- <button class="btn btn-outline-primary" @click="complete(item.id)">完成</button>
                <button class="btn btn-outline-danger" @click="remove(idx)">删除</button> -->
                <!-- <TodoButton class="btn-outline-primary" @click.native="complete(item.id)">
                    完成
                </TodoButton>
                <TodoButton class="btn-outline-danger" @click.native="remove(idx)">删除</TodoButton> -->
                <TodoButton class="btn-outline-primary" @click.native="completeItem(item.id)">
                    完成
                </TodoButton>
                <TodoButton class="btn-outline-danger" @click.native="removeItem(idx)">删除</TodoButton>
            </div>
        </td>
    </tr>
</template>
<script>
import TodoButton from './TodoButton.vue'
// import Bus from './Bus'

export default {
    name:'TodoItem',
    props:['item','idx',
    // 'complete','remove'
    ],
    data(){
        return {
            
        }
    },
    components:{
        TodoButton
    },
    methods:{
        completeItem(id){
            // Bus.$emit('complete',id)
            this.$root.$emit('complete',id)
        },
        removeItem(idx){
            // Bus.$emit('remove',idx)
            this.$root.$emit('remove',idx)
        }
    }
}
</script>
