// 三阶段/w6_Redux/src/views/Login/Login.jsx
import React from 'react'
import { Form, Input, Checkbox, Button, message } from 'antd'
import request from '@/utils/request'
// import store from '@/store'
import { connect } from 'react-redux';
import userAction from '@/store/actions/user'
import { Redirect } from 'react-router';

const layout = {
    labelCol: { span: 6 },
    wrapperCol: { span: 16 },
};
const tailLayout = {
    wrapperCol: { offset: 6, span: 16 },
};

function Login(props) {
    console.log("Login.props=", props);
    const rules = {
        username: [{ required: true, message: '请输入用户名' }],
        password: [{ required: true, message: '请输入密码' }],
        vcode: [{ required: true, message: '请输入验证码' }],
    }
    const onFinish = async (values) => {
        console.log('values=', values);

        // const data = await request.post('/login', {
        //     ...values
        // })
        // if (data.code === 200) {
        //     // store.dispatch({type:'login',user:data.data})
        //     props.login(data.data);
        //     props.history.replace('/home')
        //     message.success('登录成功')
        // }
        props.login(values);
        // if (result.code === 200) {
        //     props.history.replace('/home')
        //     message.success('登录成功')
        // }

    }
    return (
        props.isLogin ? 
        <Redirect to="/home" />
        :
        <div>
            <h1>用户登录</h1>
            <Form
                {...layout}
                name="basic"
                initialValues={{ remember: true }}
                onFinish={onFinish}
            >
                <Form.Item
                    label="用户名"
                    name="username"
                    rules={rules.username}
                >
                    <Input />
                </Form.Item>

                <Form.Item
                    label="密码"
                    name="password"
                    rules={rules.password}
                >
                    <Input.Password />
                </Form.Item>
                {/* <Form.Item
                label="验证码"
                name="vcode"
                rules={rules.vcode}
            >
                <Input addonAfter={<span>dfsadf</span>} />
            </Form.Item> */}

                <Form.Item {...tailLayout} name="remember" valuePropName="checked">
                    <Checkbox>下次免登录</Checkbox>
                </Form.Item>

                <Form.Item {...tailLayout}>
                    <Button type="primary" htmlType="submit">
                        登录
                </Button>
                </Form.Item>
            </Form>
        </div>
    )
}
const mapStateToProps = (state)=>({isLogin:!!state.user.userInfo});
const mapDispatchToProps = dispatch => ({
    login(data) {
        // dispatch({type:'login',user})
        // dispatch(userAction.login(user))
        // return dispatch(userAction.loginAsync(data));
        dispatch({ type: 'USER_LOGIN_ASYNC', user: data })
    }
})
Login = connect(mapStateToProps, mapDispatchToProps)(Login)

export default Login;

// 三阶段/w3_VueRouter/myapp/src/views/Login.vue
<template>
  <div>
    <h1>用户登录</h1>
    <el-form
      :model="formData"
      :rules="rules"
      ref="ruleForm"
      label-width="100px"
      status-icon
    >
      <el-form-item
        label="用户名"
        prop="username"
      >
        <el-input v-model="formData.username" />
      </el-form-item>
      <el-form-item
        label="密码"
        prop="password"
      >
        <el-input
          type="password"
          v-model="formData.password"
          show-password
        />
      </el-form-item>
      <el-form-item
        label="验证码"
        prop="vcode"
      >
        <el-input v-model="formData.vcode">
          <template v-slot:append>
            <span
              v-html="imgvcode"
              @click="getVcode"
              class="vcode"
            ></span>
          </template>
        </el-input>
      </el-form-item>

      <el-form-item>
        <el-button
          type="primary"
          @click="submitForm"
        >登录</el-button>
      </el-form-item>
    </el-form>
  </div>
</template>
<script>
export default {
  name: "Login",
  data() {
    return {
      imgvcode: "",
      formData: {
        username: "",
        password: "",
        vcode: ""
      },
      rules: {
        username: [
          { required: true, message: "请输入用户名", trigger: "blur" }
        ],
        password: [{ required: true, message: "请输入密码", trigger: "blur" }],
        vcode: [{ required: true, message: "请求输入验证码", trigger: "blur" }]
      }
    };
  },
  methods: {
    submitForm() {
      this.$refs.ruleForm.validate(valid => {
        // valid 为boolean，表示表单是否校验通过
        console.log("valid", valid);
        if (valid) {
          const { username, password, vcode } = this.formData;
          this.$request
            .post("/login", {
              username,
              password,
              vcode
            })
            .then(data => {
              if (data.code === 200) {
                const { targetUrl = "/mine" } = this.$route.query;

                // localStorage.setItem("userInfo", JSON.stringify(data.data));
                // this.$store.commit("login", data.data);

                // 设置命名空间后的写法：
                this.$store.commit("user/login", data.data);
                
                this.$router.push(targetUrl);
              } else if (data.code === 401) {
                this.$message.error("验证码错误");
              }
            });
        }
      });
    },
    getVcode() {
      this.$request.get("/vcode/picture").then(data => {
        this.imgvcode = data.data;
      });
    }
  },
  created() {
    console.log("Login=", this);
    // hard code
    this.getVcode();
  }
};
</script>
<style>
.vcode {
  display: block;
  margin: 0 -20px;
  width: 120px;
  height: 38px;
  overflow: hidden;
}
.vcode svg {
  width: 120px;
  height: 40px;
}
</style>
